"""added unique constraint to Data

Revision ID: e273259847c5
Revises: 37ba009a9ba8
Create Date: 2024-02-17 20:30:51.060735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e273259847c5'
down_revision: Union[str, None] = '37ba009a9ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_owner_id_uc', 'datas', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_owner_id_uc', 'datas', type_='unique')
    # ### end Alembic commands ###
